DELETE http://localhost:3003/api/blogs/641acce5891831ffbdfb1bf6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMTIzMjMxIiwiaWQiOiI2NDA5ZjhmYzQ4MzhlYzc2YjM3NmNjZGQiLCJpYXQiOjE2Nzk0NzUyNjd9.NtiHTr768sVdHsCxiGmhuHUSg97wyVaeyheaIXIC3Ok
